services:
  - type: web
    name: water-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand:       
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9